# Welcome to Jekyll!
# Configuration for Parmida Jabari's personal site

# Theme Settings
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Parmida Jabari"
title_separator: "-"
subtitle: "Innovating with AI, Neuroscience, and Robotics"
name: "Parmida Jabari"
description: "Explore my journey through AI, machine learning, neuroscience, and innovative research."
url: "https://your-website.com" # Replace with your website's URL
baseurl: "/"
repository: "parmidajabbari/personal-site"
teaser: "/assets/images/profile.jpg"
logo: "/assets/images/logo.png"
masthead_title: "Parmida Jabari"
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Parmida Jabari"
copyright_url: "https://your-website.com"

comments:
  provider: "utterances"
  utterances:
    repo: "parmidajabbari/personal-site-comments"
    theme: "github-light"
    issue_term: "pathname"

search: true
search_provider: lunr

# SEO Related
google_site_verification: "YOUR_GOOGLE_VERIFICATION_CODE"

# Social Sharing
og_image: "/assets/images/og-image.png"
social:
  type: "Person"
  name: "Parmida Jabari"
  links:
    - "https://github.com/parmidajabbari"
    - "https://linkedin.com/in/parmida-jabbari-a61a15213/"
    - "https://scholar.google.com/"

# Analytics
analytics:
  provider: "google"
  google:
    tracking_id: "UA-XXXXXXXXX-X"

# Site Author
author:
  name: "Parmida Jabari"
  avatar: "/assets/images/avatar.jpg"
  bio: "AI researcher passionate about neuroscience and robotics. Currently exploring cutting-edge applications in healthcare and automation."
  location: "Tehran, Iran"
  email: "parmidajabbari@gmail.com"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parmidajabbari"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/parmida-jabbari-a61a15213/"

# Site Footer
footer:
  links:
    - label: "Publications"
      icon: "fas fa-fw fa-book"
      url: "/publications/"
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/cv/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/parmidajabbari"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/parmida-jabbari-a61a15213/"

# Academic Projects
academic_projects:
  - title: "Dose Prediction Using Radiomic Features"
    description: "A machine learning model for cancer treatment dose prediction, achieving an R-squared of 0.8 for PET images."
    link: "https://github.com/Parmidajabbari/Cancer-Treatment-Dose-Prediction"
  - title: "Car Speed Detection Project"
    description: "Car speed detection using optical flow and machine learning."
    link: "https://github.com/parmidajabbari/car-speed-detection"
  - title: "LLM Detection Project"
    description: "Detecting AI-generated texts using the DeBERTa model."
    link: "https://github.com/Parmidajabbari/LLM-Detection"

# Publications Section
publications:
  - title: "Autonomous Rearrangement Planning Using Object Similarity Learning"
    conference: "ICROM 2024"
    date: "October 2024"
    link: "https://ieeexplore.ieee.org/document/XXXXX"

  - title: "Machine Learning-Based Dose Prediction in [177Lu]Lu-PSMA-617 Radioligand Therapy"
    journal: "Radio Journal"
    status: "Under Review"
    date: "May 2024"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
